name: openapi

on:
  push:
    branches: [ "main" ]
    paths:
      - 'openapi.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build 
      run: |
        swift run swift-openapi-generator generate \
        --mode types --mode server \
        --output-directory Sources/EndPoint/OpenAPI/ \
        openapi.yaml

    - uses: peter-evans/create-pull-request@v6
      with:
        branch: _api
        commit-message: Update OpenAPI generated
        team-reviewers: ios_wg_recruitment
