// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// Get fortune for given person
    ///
    /// This endpoint returns the fortune of a person based on their name, birthday, and blood type, as well as the current date.
    ///
    /// - Remark: HTTP `POST /my_fortune`.
    /// - Remark: Generated from `#/paths//my_fortune/post(post-my-fortune)`.
    func post_hyphen_my_hyphen_fortune(_ input: Operations.post_hyphen_my_hyphen_fortune.Input) async throws -> Operations.post_hyphen_my_hyphen_fortune.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Get fortune for given person
    ///
    /// This endpoint returns the fortune of a person based on their name, birthday, and blood type, as well as the current date.
    ///
    /// - Remark: HTTP `POST /my_fortune`.
    /// - Remark: Generated from `#/paths//my_fortune/post(post-my-fortune)`.
    internal func post_hyphen_my_hyphen_fortune(
        headers: Operations.post_hyphen_my_hyphen_fortune.Input.Headers = .init(),
        body: Operations.post_hyphen_my_hyphen_fortune.Input.Body
    ) async throws -> Operations.post_hyphen_my_hyphen_fortune.Output {
        try await post_hyphen_my_hyphen_fortune(Operations.post_hyphen_my_hyphen_fortune.Input(
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {
    internal static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://yumemi-ios-junior-engineer-codecheck.app.swift.cloud",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
internal enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/MyFortuneRequest`.
        internal struct MyFortuneRequest: Codable, Hashable, Sendable {
            /// Target's name.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/name`.
            internal var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/birthday`.
            internal struct birthdayPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/birthday/value1`.
                internal var value1: Components.Schemas.YearMonthDay
                /// Target's birthday.
                ///
                /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/birthday/value2`.
                internal var value2: OpenAPIRuntime.OpenAPIValueContainer
                /// Creates a new `birthdayPayload`.
                ///
                /// - Parameters:
                ///   - value1:
                ///   - value2: Target's birthday.
                internal init(
                    value1: Components.Schemas.YearMonthDay,
                    value2: OpenAPIRuntime.OpenAPIValueContainer
                ) {
                    self.value1 = value1
                    self.value2 = value2
                }
                internal init(from decoder: any Decoder) throws {
                    value1 = try .init(from: decoder)
                    value2 = try .init(from: decoder)
                }
                internal func encode(to encoder: any Encoder) throws {
                    try value1.encode(to: encoder)
                    try value2.encode(to: encoder)
                }
            }
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/birthday`.
            internal var birthday: Components.Schemas.MyFortuneRequest.birthdayPayload
            /// Target's blood type.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/blood_type`.
            @frozen internal enum blood_typePayload: String, Codable, Hashable, Sendable {
                case a = "a"
                case b = "b"
                case ab = "ab"
                case o = "o"
            }
            /// Target's blood type.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/blood_type`.
            internal var blood_type: Components.Schemas.MyFortuneRequest.blood_typePayload
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/today`.
            internal struct todayPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/today/value1`.
                internal var value1: Components.Schemas.YearMonthDay
                /// Today's date.
                ///
                /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/today/value2`.
                internal var value2: OpenAPIRuntime.OpenAPIValueContainer
                /// Creates a new `todayPayload`.
                ///
                /// - Parameters:
                ///   - value1:
                ///   - value2: Today's date.
                internal init(
                    value1: Components.Schemas.YearMonthDay,
                    value2: OpenAPIRuntime.OpenAPIValueContainer
                ) {
                    self.value1 = value1
                    self.value2 = value2
                }
                internal init(from decoder: any Decoder) throws {
                    value1 = try .init(from: decoder)
                    value2 = try .init(from: decoder)
                }
                internal func encode(to encoder: any Encoder) throws {
                    try value1.encode(to: encoder)
                    try value2.encode(to: encoder)
                }
            }
            /// - Remark: Generated from `#/components/schemas/MyFortuneRequest/today`.
            internal var today: Components.Schemas.MyFortuneRequest.todayPayload
            /// Creates a new `MyFortuneRequest`.
            ///
            /// - Parameters:
            ///   - name: Target's name.
            ///   - birthday:
            ///   - blood_type: Target's blood type.
            ///   - today:
            internal init(
                name: Swift.String,
                birthday: Components.Schemas.MyFortuneRequest.birthdayPayload,
                blood_type: Components.Schemas.MyFortuneRequest.blood_typePayload,
                today: Components.Schemas.MyFortuneRequest.todayPayload
            ) {
                self.name = name
                self.birthday = birthday
                self.blood_type = blood_type
                self.today = today
            }
            internal enum CodingKeys: String, CodingKey {
                case name
                case birthday
                case blood_type
                case today
            }
        }
        /// - Remark: Generated from `#/components/schemas/MyFortuneResponse`.
        internal struct MyFortuneResponse: Codable, Hashable, Sendable {
            /// Result prefecture's name.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/name`.
            internal var name: Swift.String
            /// Result prefecture's brief instruction.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/brief`.
            internal var brief: Swift.String
            /// Result prefecture's capital city.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/capital`.
            internal var capital: Swift.String
            /// Result prefecture's citizen date (if it has one).
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/citizen_day`.
            internal struct citizen_dayPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/citizen_day/value1`.
                internal var value1: Components.Schemas.MonthDay
                /// Creates a new `citizen_dayPayload`.
                ///
                /// - Parameters:
                ///   - value1:
                internal init(value1: Components.Schemas.MonthDay) {
                    self.value1 = value1
                }
                internal init(from decoder: any Decoder) throws {
                    value1 = try .init(from: decoder)
                }
                internal func encode(to encoder: any Encoder) throws {
                    try value1.encode(to: encoder)
                }
            }
            /// Result prefecture's citizen date (if it has one).
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/citizen_day`.
            internal var citizen_day: Components.Schemas.MyFortuneResponse.citizen_dayPayload?
            /// Whether result prefecture has a coast line or not.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/has_coast_line`.
            internal var has_coast_line: Swift.Bool
            /// Result prefecture's logo's URL.
            ///
            /// - Remark: Generated from `#/components/schemas/MyFortuneResponse/logo_url`.
            internal var logo_url: Swift.String
            /// Creates a new `MyFortuneResponse`.
            ///
            /// - Parameters:
            ///   - name: Result prefecture's name.
            ///   - brief: Result prefecture's brief instruction.
            ///   - capital: Result prefecture's capital city.
            ///   - citizen_day: Result prefecture's citizen date (if it has one).
            ///   - has_coast_line: Whether result prefecture has a coast line or not.
            ///   - logo_url: Result prefecture's logo's URL.
            internal init(
                name: Swift.String,
                brief: Swift.String,
                capital: Swift.String,
                citizen_day: Components.Schemas.MyFortuneResponse.citizen_dayPayload? = nil,
                has_coast_line: Swift.Bool,
                logo_url: Swift.String
            ) {
                self.name = name
                self.brief = brief
                self.capital = capital
                self.citizen_day = citizen_day
                self.has_coast_line = has_coast_line
                self.logo_url = logo_url
            }
            internal enum CodingKeys: String, CodingKey {
                case name
                case brief
                case capital
                case citizen_day
                case has_coast_line
                case logo_url
            }
        }
        /// - Remark: Generated from `#/components/schemas/YearMonthDay`.
        internal struct YearMonthDay: Codable, Hashable, Sendable {
            /// Year number
            ///
            /// - Remark: Generated from `#/components/schemas/YearMonthDay/year`.
            internal var year: Swift.Int
            /// Month number
            ///
            /// - Remark: Generated from `#/components/schemas/YearMonthDay/month`.
            internal var month: Swift.Int
            /// Day number
            ///
            /// - Remark: Generated from `#/components/schemas/YearMonthDay/day`.
            internal var day: Swift.Int
            /// Creates a new `YearMonthDay`.
            ///
            /// - Parameters:
            ///   - year: Year number
            ///   - month: Month number
            ///   - day: Day number
            internal init(
                year: Swift.Int,
                month: Swift.Int,
                day: Swift.Int
            ) {
                self.year = year
                self.month = month
                self.day = day
            }
            internal enum CodingKeys: String, CodingKey {
                case year
                case month
                case day
            }
        }
        /// - Remark: Generated from `#/components/schemas/MonthDay`.
        internal struct MonthDay: Codable, Hashable, Sendable {
            /// Month number
            ///
            /// - Remark: Generated from `#/components/schemas/MonthDay/month`.
            internal var month: Swift.Int
            /// Day number
            ///
            /// - Remark: Generated from `#/components/schemas/MonthDay/day`.
            internal var day: Swift.Int
            /// Creates a new `MonthDay`.
            ///
            /// - Parameters:
            ///   - month: Month number
            ///   - day: Day number
            internal init(
                month: Swift.Int,
                day: Swift.Int
            ) {
                self.month = month
                self.day = day
            }
            internal enum CodingKeys: String, CodingKey {
                case month
                case day
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    internal enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    internal enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    internal enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    internal enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
internal enum Operations {
    /// Get fortune for given person
    ///
    /// This endpoint returns the fortune of a person based on their name, birthday, and blood type, as well as the current date.
    ///
    /// - Remark: HTTP `POST /my_fortune`.
    /// - Remark: Generated from `#/paths//my_fortune/post(post-my-fortune)`.
    internal enum post_hyphen_my_hyphen_fortune {
        internal static let id: Swift.String = "post-my-fortune"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/my_fortune/POST/header`.
            internal struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/my_fortune/POST/header/API-Version`.
                @frozen internal enum API_hyphen_VersionPayload: String, Codable, Hashable, Sendable {
                    case v1 = "v1"
                }
                /// API version you'd like to use in your sending request. Currently only `v1` available. If you don't attach this parameter in your header, system will use the latest API version.
                ///
                /// - Remark: Generated from `#/paths/my_fortune/POST/header/API-Version`.
                internal var API_hyphen_Version: Operations.post_hyphen_my_hyphen_fortune.Input.Headers.API_hyphen_VersionPayload?
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.post_hyphen_my_hyphen_fortune.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - API_hyphen_Version: API version you'd like to use in your sending request. Currently only `v1` available. If you don't attach this parameter in your header, system will use the latest API version.
                ///   - accept:
                internal init(
                    API_hyphen_Version: Operations.post_hyphen_my_hyphen_fortune.Input.Headers.API_hyphen_VersionPayload? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.post_hyphen_my_hyphen_fortune.AcceptableContentType>] = .defaultValues()
                ) {
                    self.API_hyphen_Version = API_hyphen_Version
                    self.accept = accept
                }
            }
            internal var headers: Operations.post_hyphen_my_hyphen_fortune.Input.Headers
            /// - Remark: Generated from `#/paths/my_fortune/POST/requestBody`.
            @frozen internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/my_fortune/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.MyFortuneRequest)
            }
            internal var body: Operations.post_hyphen_my_hyphen_fortune.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            internal init(
                headers: Operations.post_hyphen_my_hyphen_fortune.Input.Headers = .init(),
                body: Operations.post_hyphen_my_hyphen_fortune.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/my_fortune/POST/responses/200/content`.
                @frozen internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/my_fortune/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.MyFortuneResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.MyFortuneResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.post_hyphen_my_hyphen_fortune.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.post_hyphen_my_hyphen_fortune.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Success
            ///
            /// - Remark: Generated from `#/paths//my_fortune/post(post-my-fortune)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.post_hyphen_my_hyphen_fortune.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.post_hyphen_my_hyphen_fortune.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
